---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
# - name: test
#   image: golang:1.11
#   commands:
#   - go test --tags oss -v ./...
#   volumes:
#   - name: gopath
#     path: /go

- name: build
  image: golang:1.11
  commands:
  - "go build --tags oss -ldflags \"-extldflags \\\\\"-static\\\\\"\" -o release/linux/amd64/drone-server github.com/drone/drone/cmd/drone-server"
  volumes:
  - name: gopath
    path: /go
  when:
    event:
    - push
    - tag

- name: publish_server
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.server.linux.amd64
    password:
      from_secret: docker_password
    repo: laszlocloud/drone-oss
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag

volumes:
- name: gopath
  temp: {}
